Импорт Numpy

In [3]:
import numpy as np

Примеры создания массивов

In [34]:
#1
import numpy as np

#2
a = np.array([1, 2, 3])      # одномерный массив из списка
print ("a:Одномерный массив из списка:", a) 

b = np.array([[1.5, 2, 3], [4, 5, 6]])   # двумерный массив из списков
print ("b:Двумерный массив из списка:\n", b) 

aa=np.zeros((6, 9)) # двумерный массив из нулей, размером 6 на 9
print ("aa:Двумерный массив из нулей с использованием .zeros:\n", aa) 

bb=np.ones((4, 6)) # двумерный массив из нулей, размером 4 на 6
print ("bb:Двумерный массив из нулей с использованием .zeros:\n", bb)

cc=np.arange(1, 35, 2) # одномерный массив - последовательность от 1 до 35 с шагом 2
print ("cc:Одномерный массив из последовательности с использованием arange:\n", cc)

#3
print("bb:Форма двумерного массива:", bb.shape)      # shape получает форму двумерного массива
print("bb:Тип данных двумерного массива:", bb.dtype)    # dtype получает тип данных в заданном массиве

#4
print("cc:Первый элемент:", cc[0])             # обращение по индексу
print("cc:Последний элемент:", cc[-1])        # обращение по индексу с конца

print("cc:Элементы с 4 по 7-1 индекс (с нуля):", cc[4:7])    # срезы
print("cc:Элементы в обратном порядке:", cc[::-1]) 

#5
print("a + b =\n", a + b)          # сумма одномерного массива с двумерным

print("cc:Среднее значение:", cc.mean())    # среднее значение массива
print("cc:Минимальное значение:", cc.min())       # минимальный элемент
print("cc:Максимальное значение:", cc.max())        # максимальный элемент
print("cc:Сумма всех элементов:", cc.sum())        # сумма элементов


a:Одномерный массив из списка: [1 2 3]
b:Двумерный массив из списка:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
aa:Двумерный массив из нулей с использованием .zeros:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
bb:Двумерный массив из нулей с использованием .zeros:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
cc:Одномерный массив из последовательности с использованием arange:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
bb:Форма двумерного массива: (4, 6)
bb:Тип данных двумерного массива: float64
cc:Первый элемент: 1
cc:Последний элемент: 33
cc:Элементы с 4 по 7-1 индекс (с нуля): [ 9 11 13]
cc:Элементы в обратном порядке: [33 31 29 27 25 23 21 19 17 15 13 11  9  7  5  3  1]
a + b =
 [[2.5 4.  6. ]
 [5.  7.  9. ]]
cc:Среднее значение: 17.0
cc:Минимальное значение: 1
cc:Максимальное значение: 33
cc:Сумма всех элеме